version: '3.9'

services:
  ###################
  crawler:
    build:
      context: ./crawler
      dockerfile: ./Dockerfile
    env_file:
     - production.env      
    depends_on:
      - mongo  
  ###################
  schedule:
    build:
      context: ./schedule
      dockerfile: ./Dockerfile
    env_file:
     - production.env          
    depends_on:
      - crawler
  ###################
  web_site:
    build:
      context: ./web_site
      dockerfile: ./Dockerfile
    env_file:
     - production.env    
    depends_on:
      - crawler  
  ###################
  reverse_proxy_server:
    build:
      context: ./reverse_proxy_server
      dockerfile: ./Dockerfile 
    ports:
    - "5269:80"
    depends_on:
      - crawler
      - web_site
###################
  mongo:
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - mongodb:/data/db
###################
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5469:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
            - mongo                           
volumes:
  scrapyd-logs-data:
  scrapyd-dbs-data:
  mongodb: